# Generated by Django 3.2.12 on 2022-02-14 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(help_text='Enter age of patient')),
                ('sex', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], help_text='Sex of patient', max_length=1)),
                ('chest', models.CharField(blank=True, choices=[('TA', 'Typical Angina'), ('ATA', 'Atypical Angina'), ('NAP', ' Non-Anginal Pain'), ('ASY', 'Asymptomatic')], help_text='Chest Pain Type of patient', max_length=3)),
                ('restingBP', models.IntegerField(help_text='Enter Resting BP of patient')),
                ('cholesterol', models.IntegerField(help_text='Enter Cholesterol of patient')),
                ('fastingBS', models.IntegerField(help_text='Enter fasting blood sugar of patient')),
                ('ecg', models.CharField(blank=True, choices=[('Normal', 'Normal'), ('ST', 'having ST-T wave abnormality'), ('LVH', 'showing probable or definite left ventricular hypertrophy by Estes criteria')], help_text='Resting ECG analysis of patient', max_length=8)),
                ('maxHR', models.IntegerField(help_text='Enter the max heart rate of the patient', max_length=3)),
                ('exerciseAngina', models.CharField(choices=[('Y', 'yes'), ('N', 'no')], help_text='Does the patient experience exercise induced angina?', max_length=1)),
                ('oldPeak', models.FloatField(help_text='Enter oldpeak measured in depression', max_length=4)),
                ('stSlope', models.CharField(choices=[('Up', 'Upwards'), ('Flat', 'Flat'), ('Down', 'Downwards')], help_text='Enter the slope of the peak exercise ST segment direction for the patient', max_length=10)),
            ],
        ),
    ]
