# Generated by Django 3.2.12 on 2022-02-14 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_patient_maxhr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='ecg',
            field=models.CharField(blank=True, choices=[('Normal', 'Normal'), ('ST', 'Having ST-T wave abnormality'), ('LVH', 'Left Ventricular Hypertrophy')], help_text='Resting ECG analysis of patient', max_length=8),
        ),
        migrations.AlterField(
            model_name='patient',
            name='exerciseAngina',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], help_text='Does the patient experience exercise induced angina?', max_length=3),
        ),
        migrations.AlterField(
            model_name='patient',
            name='stSlope',
            field=models.CharField(choices=[('Upwards', 'Upwards'), ('Flat', 'Flat'), ('Down', 'Down')], help_text='Enter the slope of the peak exercise ST segment direction for the patient', max_length=10),
        ),
    ]
