# Generated by Django 3.2.12 on 2022-02-15 00:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20220214_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientPrediction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular prediction', primary_key=True, serialize=False)),
            ],
        ),
    ]
