# Generated by Django 3.2.12 on 2022-02-15 13:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_patientprediction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular patient', primary_key=True, serialize=False),
        ),
    ]
