# Generated by Django 3.2.12 on 2022-02-15 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_patient_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PatientPrediction',
        ),
        migrations.AlterField(
            model_name='patient',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
