# Generated by Django 3.2.12 on 2022-02-19 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20220217_1209'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccuracyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
